// Sample catalogue for the prototype.
// Names, ratings and categories come from the product brief. Areas, hours, events,
// drive times and vibe attributes are ILLUSTRATIVE placeholders until verified.
//
// Time convention: a "service day" runs 6:00 → 6:00 next morning, so hours are
// expressed 6–30 (e.g. 26 = 2 AM the following morning). Day index 0 = Sunday.

const every = (o, c) => [0, 1, 2, 3, 4, 5, 6].map(() => [o, c])
const only = (days, o, c) => [0, 1, 2, 3, 4, 5, 6].map((d) => (days.includes(d) ? [o, c] : null))

export const AREAS = ['Wuse II', 'Maitama', 'Jabi', 'Garki', 'Asokoro', 'Gwarinpa']

export const MUSIC = ['Afrobeats', 'Amapiano', 'Hip-hop', 'House', 'Highlife', 'Live band', 'Lounge / R&B', 'Jazz', 'Acoustic']

export const VENUES = [
  {
    id: 'boom-boom-room',
    name: 'The Boom Boom Room',
    category: 'Night club',
    kind: 'club',
    rating: 4.5,
    area: 'Wuse II',
    mins: 12,
    price: 4,
    music: ['Afrobeats', 'Amapiano', 'Hip-hop'],
    hours: only([4, 5, 6], 22, 29),
    dress: 'Smart, no shorts or slides',
    age: '21+ · mostly 25–35',
    energy: 'High',
    noise: 'Loud',
    conversation: 'Difficult',
    bestFor: ['Dancing', 'Groups', 'Birthdays'],
    tags: ['dance', 'late', 'bottle service', 'groups'],
    events: { 5: { title: 'Amapiano Fridays', time: '11 PM', by: 'DJ Kaywise (sample)' }, 6: { title: 'Saturday Takeover', time: '11:30 PM', by: 'Resident DJs' } },
    weight: 1.1,
    history: 'strong',
    hue: 8,
    phone: '+234 800 000 0101',
    reserve: true,
    blurb: 'Late-night room for people who come to dance. Narrow schedule, packed when it is on.',
  },
  {
    id: 'tokyo-nightlife',
    name: 'Tokyo Nightlife Abuja',
    category: 'Lounge bar',
    kind: 'lounge',
    rating: 4.3,
    area: 'Wuse II',
    mins: 10,
    price: 3,
    music: ['Afrobeats', 'Lounge / R&B', 'Amapiano'],
    hours: every(18, 28),
    dress: 'Smart casual',
    age: 'Mixed · 23–40',
    energy: 'Building',
    noise: 'Loud after 11',
    conversation: 'Fine before 10',
    bestFor: ['Groups', 'Shisha', 'Pre-club'],
    tags: ['shisha', 'late', 'social', 'groups'],
    events: { 4: { title: 'Throwback Thursday', time: '9 PM', by: 'In-house DJ' } },
    weight: 1,
    history: 'strong',
    hue: 330,
    phone: '+234 800 000 0102',
    reserve: true,
    blurb: 'Lounge that turns into a party after eleven. Good place to start a night with a group.',
  },
  {
    id: 'moscow-underground',
    name: 'Moscow Underground',
    category: 'Night club',
    kind: 'club',
    rating: 4.3,
    area: 'Garki',
    mins: 18,
    price: 3,
    music: ['House', 'Amapiano', 'Afrobeats'],
    hours: only([5, 6], 23, 29),
    dress: 'Anything goes, no sportswear',
    age: '18+ · mostly 20–30',
    energy: 'High',
    noise: 'Very loud',
    conversation: 'Difficult',
    bestFor: ['Dancing', 'House heads'],
    tags: ['dance', 'late', 'underground'],
    events: { 6: { title: 'Deep House Saturday', time: 'Midnight', by: 'Guest DJ (sample)' } },
    weight: 0.95,
    history: 'thin',
    hue: 270,
    phone: '+234 800 000 0103',
    reserve: false,
    blurb: 'Basement club with a house-music crowd. Few live reports so far, so forecasts are rough.',
  },
  {
    id: 'play-imperial',
    name: 'Play Imperial Lounge',
    category: 'Lounge bar',
    kind: 'lounge',
    rating: 4.3,
    area: 'Jabi',
    mins: 15,
    price: 3,
    music: ['Afrobeats', 'Hip-hop', 'Lounge / R&B'],
    hours: every(16, 27),
    dress: 'Smart casual',
    age: 'Mixed · 25–45',
    energy: 'Medium',
    noise: 'Moderate',
    conversation: 'Easy until 11',
    bestFor: ['Groups', 'Watching football', 'After work'],
    tags: ['sports', 'social', 'outdoor', 'groups'],
    events: { 0: { title: 'Sunday Football + Grill', time: '4 PM', by: 'Venue' }, 3: { title: 'Karaoke Wednesday', time: '8 PM', by: 'Venue' } },
    weight: 0.9,
    history: 'strong',
    hue: 40,
    phone: '+234 800 000 0104',
    reserve: true,
    blurb: 'Big Jabi lounge with screens and an outdoor deck. Social, rarely rammed.',
  },
  {
    id: 'aura-lounge',
    name: 'Aura Lounge',
    category: 'Lounge bar',
    kind: 'lounge',
    rating: 4.3,
    area: 'Maitama',
    mins: 14,
    price: 4,
    music: ['Lounge / R&B', 'Afrobeats'],
    hours: every(18, 27),
    dress: 'Dress to impress',
    age: '25+ · mostly 28–40',
    energy: 'Medium',
    noise: 'Moderate',
    conversation: 'Possible',
    bestFor: ['Dates', 'Small groups', 'Cocktails'],
    tags: ['upscale', 'romantic', 'social'],
    events: {},
    weight: 0.9,
    history: 'strong',
    hue: 190,
    phone: '+234 800 000 0105',
    reserve: true,
    reportedClosed: { by: 'community', note: '3 people reported it closed tonight (private event). Last report 18 min ago.' },
    blurb: 'Upscale Maitama lounge. Usually good for a dressed-up evening with friends.',
  },
  {
    id: 'cue-bar',
    name: 'Cue Bar',
    category: 'Cocktail bar',
    kind: 'cocktail',
    rating: 4.3,
    area: 'Wuse II',
    mins: 9,
    price: 2,
    music: ['Afrobeats', 'Hip-hop', 'Acoustic'],
    hours: every(16, 26),
    dress: 'Casual',
    age: 'Mixed · 22–35',
    energy: 'Medium',
    noise: 'Moderate',
    conversation: 'Easy',
    bestFor: ['Friends', 'Pool', 'Cheap drinks'],
    tags: ['pool tables', 'social', 'budget'],
    events: { 5: { title: 'Happy Hour 5–8 PM', time: '5 PM', by: 'Venue reported' } },
    weight: 0.95,
    history: 'strong',
    hue: 150,
    phone: '+234 800 000 0106',
    reserve: false,
    // seeded community reports that disagree with the forecast (demo of "Expected 🔥 → Currently 🟡")
    seedReports: [2, 2, 1, 2, 2],
    blurb: 'Pool tables, reasonable prices and a friendly bar crowd.',
  },
  {
    id: 'cocktail-bar',
    name: 'Cocktail Bar',
    category: 'Cocktail bar',
    kind: 'cocktail',
    rating: 4.0,
    area: 'Wuse II',
    mins: 11,
    price: 3,
    music: ['Lounge / R&B', 'Jazz'],
    hours: every(17, 25),
    dress: 'Smart casual',
    age: 'Mixed · 25–40',
    energy: 'Relaxed',
    noise: 'Low–moderate',
    conversation: 'Easy',
    bestFor: ['Dates', 'Catching up', 'Cocktails'],
    tags: ['cocktails', 'romantic', 'conversation'],
    events: { 4: { title: 'Two-for-one Martinis', time: '7 PM', by: 'Venue reported' } },
    weight: 0.85,
    history: 'medium',
    hue: 290,
    phone: '+234 800 000 0107',
    reserve: true,
    blurb: 'Evening cocktail spot that stays conversational most nights.',
  },
  {
    id: 'guava',
    name: 'Guava Cocktail and Tapas Bar',
    category: 'Cocktail bar',
    kind: 'cocktail',
    rating: 4.4,
    area: 'Maitama',
    mins: 13,
    price: 3,
    music: ['Live band', 'Afrobeats', 'Jazz'],
    hours: every(12, 24),
    dress: 'Smart casual',
    age: 'Mixed · 25–45',
    energy: 'Lively',
    noise: 'Moderate',
    conversation: 'Possible',
    bestFor: ['Dates', 'Small plates', 'Live music'],
    tags: ['tapas', 'romantic', 'live music', 'outdoor'],
    events: { 5: { title: 'Live Band Friday', time: '8:30 PM', by: 'Venue reported' }, 6: { title: 'Sunset Tapas', time: '6 PM', by: 'Venue reported' } },
    weight: 0.95,
    history: 'strong',
    hue: 345,
    phone: '+234 800 000 0108',
    reserve: true,
    blurb: 'Tapas and cocktails with a live band on Fridays. Buzzy but you can still talk.',
  },
  {
    id: 'nkoyo',
    name: 'Nkoyo',
    category: 'Continental restaurant',
    kind: 'restaurant',
    rating: 4.3,
    area: 'Wuse II',
    mins: 10,
    price: 3,
    music: ['Highlife', 'Jazz'],
    hours: every(11, 23),
    dress: 'Smart casual',
    age: 'Mixed · families to 50+',
    energy: 'Relaxed',
    noise: 'Low',
    conversation: 'Easy',
    bestFor: ['Dinner', 'Dates', 'Business meals'],
    tags: ['dinner', 'romantic', 'nigerian', 'conversation', 'family'],
    events: {},
    weight: 0.9,
    history: 'strong',
    hue: 25,
    phone: '+234 800 000 0109',
    reserve: true,
    brunch: false,
    blurb: 'Nigerian and continental dishes in a calm dining room. Dinner peaks 7–9 PM.',
  },
  {
    id: 'blucabana',
    name: 'BluCabana Restaurant & Cafe',
    category: 'Restaurant',
    kind: 'restaurant',
    rating: 4.4,
    area: 'Maitama',
    mins: 14,
    price: 3,
    music: ['Afrobeats', 'Acoustic'],
    hours: every(10, 24),
    dress: 'Casual',
    age: 'Mixed · 22–45',
    energy: 'Buzzing at brunch',
    noise: 'Moderate',
    conversation: 'Easy',
    bestFor: ['Brunch', 'Groups', 'Outdoor'],
    tags: ['brunch', 'outdoor', 'groups', 'bottomless', 'family'],
    events: { 6: { title: 'Bottomless Brunch', time: '12 PM', by: 'Venue reported' }, 0: { title: 'Sunday Brunch + DJ', time: '1 PM', by: 'Venue reported' } },
    weight: 0.95,
    history: 'strong',
    hue: 205,
    phone: '+234 800 000 0110',
    reserve: true,
    brunch: true,
    maxLevel: 4,
    blurb: 'Poolside-style restaurant that gets loud and social at weekend brunch.',
  },
  {
    id: 'saffron',
    name: 'Saffron Cafe',
    category: 'Coffee shop',
    kind: 'cafe',
    rating: 4.3,
    area: 'Jabi',
    mins: 16,
    price: 2,
    music: ['Acoustic', 'Jazz'],
    hours: every(8, 20),
    dress: 'Casual',
    age: 'Mixed',
    energy: 'Calm',
    noise: 'Low',
    conversation: 'Easy',
    bestFor: ['Coffee', 'Working', 'Quiet catch-up'],
    tags: ['coffee', 'quiet', 'conversation', 'family', 'brunch'],
    events: {},
    weight: 0.8,
    history: 'medium',
    hue: 45,
    phone: '+234 800 000 0111',
    reserve: false,
    brunch: true,
    blurb: 'Quiet coffee shop. Good laptop spot on weekdays.',
  },
  {
    id: 'cafe-flour',
    name: 'Café Flour',
    category: 'Cafe',
    kind: 'cafe',
    rating: 4.4,
    area: 'Asokoro',
    mins: 19,
    price: 2,
    music: ['Acoustic'],
    hours: every(7, 19),
    dress: 'Casual',
    age: 'Mixed · families welcome',
    energy: 'Calm',
    noise: 'Low',
    conversation: 'Easy',
    bestFor: ['Brunch', 'Pastries', 'Families'],
    tags: ['bakery', 'brunch', 'quiet', 'family', 'outdoor'],
    events: {},
    weight: 0.85,
    history: 'medium',
    hue: 30,
    phone: '+234 800 000 0112',
    reserve: false,
    brunch: true,
    blurb: 'Bakery-café with a garden. Busy late morning on weekends, calm otherwise.',
  },
]

export const VIBES = [
  { id: 'popping', label: 'Popping', note: 'Packed, loud, dancing', glyph: '🔥' },
  { id: 'social', label: 'Social', note: 'Busy enough to mingle', glyph: '🍸' },
  { id: 'chill', label: 'Chill', note: 'Relaxed, room to breathe', glyph: '🌙' },
  { id: 'date', label: 'Date night', note: 'Quiet enough to talk', glyph: '❤️' },
  { id: 'dinner', label: 'Dinner', note: 'Proper food, good room', glyph: '🍽' },
  { id: 'brunch', label: 'Brunch', note: 'Daytime, switches mode', glyph: '🥂' },
]
